name: build-image

on:
  push:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'build-image.yml'
      - 'cmd/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'build-image.yml'
      - 'cmd/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v2
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/image-detector
          tags: |
            type=schedule
            type=sha
            type=ref,event=branch
            type=raw,latest
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner }}/image-detector:${{ steps.meta.outputs.tags }}
          format: sarif
          exit-code: ${{ github.event_name == 'pull_request' && '1' || '0' }}
          severity: CRITICAL,HIGH,MEDIUM
          ignore-unfixed: true
          vuln-type: os,library
          output: trivy.sarif

      - name: Upload Trivy Report
        if: github.event_name == 'push'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
