name: build-image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - 'Dockerfile'
      - 'build-image.yml'
      - 'cmd/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build-image.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'Dockerfile'
      - 'build-image.yml'
      - 'cmd/**'
      - 'pkg/**'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/build-image.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        if: github.event_name == 'push'
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ghcr.io/kacpermalachowski/image-detector
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
      - uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name == 'push' }}
          load: ${{ github.event_name != 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - uses: aquasecurity/trivy-action@0.32.0
        with:
          image-ref: ghcr.io/kacpermalachowski/image-detector:main-${{ github.sha }}
          format: ${{ github.event_name == 'pull_request' && 'table' || 'sarif' }}
          exit-code: ${{ github.event_name == 'pull_request' && '1' || '0' }}
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          vuln-type: os,library
          output: trivy.sarif

      - name: Upload Trivy Report
        if: github.event_name == 'push'
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
