name: release

on:
  push:
    branches:
      - main
    paths:
      - 'action.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5

      - run: |
          TAG="v$(date +'%Y%m%d')-$(echo ${{ github.sha }} | cut -c1-8)"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
        id: set-tag

      - uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          tag: ${{ steps.set-tag.outputs.tag }}

